### ISSUE TITLE
model not recognized when objectname is 'model'

### ISSUE THREAD

**Issue by luerhard** [methodds/stmInsights#7]
I just had a revealing moment, when i tried to read in my .RData object and the model was not recognized. When i change the name of the model object from "model" to "model_109" it works fine. Maybe this should be mentioned anywhere.

Otherwise great tool !

Greetings,
Lukas

**Comment by cschwem2er** [comment]
Hi Lukas,

I think this is related to #4, which unfortunately is not fixed yet: stminsights currently uses the global R environment and, because "model" is my generic internal name for passing along model objects, this might result in your object not being recognized. I will close this issue here, but many thanks for letting me know.
